<?php
/**
 * Docs Manager plugin for Craft CMS 5.x
 *
 * @link      https://lindemannrock.com
 * @copyright Copyright (c) 2026 LindemannRock
 */

namespace lindemannrock\docsmanager\services;

use craft\base\Component;
use craft\helpers\FileHelper;
use lindemannrock\docsmanager\DocsManager;
use lindemannrock\logginglibrary\traits\LoggingTrait;

/**
 * Docs Generator Service
 *
 * Generates documentation files from plugin code:
 * - Auto-generates reference docs (config, variables, commands)
 * - Creates boilerplate manual docs
 * - Manages sidebar.json
 * - Tracks generated files in .docs-meta.json
 *
 * @since 5.0.0
 */
class DocsGeneratorService extends Component
{
    use LoggingTrait;

    public function init(): void
    {
        parent::init();
        $this->setLoggingHandle('docs-manager');
    }

    /**
     * Generate all documentation for a plugin
     *
     * @param string $pluginPath Path to plugin root
     * @param bool $force Force overwrite existing files
     * @return array Results of generation
     */
    public function generate(string $pluginPath, bool $force = false): array
    {
        $results = [
            'success' => true,
            'generated' => [],
            'skipped' => [],
            'errors' => [],
        ];

        // Get plugin info from composer.json
        $composerPath = $pluginPath . '/composer.json';
        if (!file_exists($composerPath)) {
            $results['success'] = false;
            $results['errors'][] = 'composer.json not found';
            return $results;
        }

        $composer = json_decode(file_get_contents($composerPath), true);
        $pluginName = $composer['extra']['name'] ?? 'Unknown Plugin';
        $pluginHandle = $composer['extra']['handle'] ?? 'unknown';

        // Ensure docs directory exists
        $docsPath = $pluginPath . '/docs';
        if (!is_dir($docsPath)) {
            FileHelper::createDirectory($docsPath);
        }

        // Load existing meta or create new
        $meta = $this->loadMeta($pluginPath);

        // Extract data from code
        $extracted = DocsManager::getInstance()->codeExtractor->extractAll($pluginPath);

        // Generate auto-generated files
        $autoGenerated = [];

        // 1. Configuration reference
        if (!empty($extracted['settings'])) {
            $configPath = 'get-started/configuration.md';
            $result = $this->generateConfigurationDoc($docsPath, $extracted['settings'], $pluginName, $meta, $force);
            if ($result['written']) {
                $results['generated'][] = $configPath;
                $autoGenerated[] = $configPath;
            } else {
                $results['skipped'][] = $configPath . ' (already exists)';
            }
        }

        // 2. Template variables reference
        if (!empty($extracted['variables'])) {
            $varsPath = 'developers/template-variables.md';
            $result = $this->generateVariablesDoc($docsPath, $extracted['variables'], $pluginName, $pluginHandle, $meta, $force);
            if ($result['written']) {
                $results['generated'][] = $varsPath;
                $autoGenerated[] = $varsPath;
            } else {
                $results['skipped'][] = $varsPath . ' (already exists)';
            }
        }

        // 3. Console commands reference
        if (!empty($extracted['commands'])) {
            $cmdsPath = 'developers/console-commands.md';
            $result = $this->generateCommandsDoc($docsPath, $extracted['commands'], $pluginName, $meta, $force);
            if ($result['written']) {
                $results['generated'][] = $cmdsPath;
                $autoGenerated[] = $cmdsPath;
            } else {
                $results['skipped'][] = $cmdsPath . ' (already exists)';
            }
        }

        // 4. Permissions reference
        if (!empty($extracted['permissions'])) {
            $permsPath = 'developers/permissions.md';
            $result = $this->generatePermissionsDoc($docsPath, $extracted['permissions'], $pluginName, $meta, $force);
            if ($result['written']) {
                $results['generated'][] = $permsPath;
                $autoGenerated[] = $permsPath;
            } else {
                $results['skipped'][] = $permsPath . ' (already exists)';
            }
        }

        // 5. Twig globals reference
        if (!empty($extracted['twigGlobals'])) {
            $globalsPath = 'developers/twig-globals.md';
            $result = $this->generateTwigGlobalsDoc($docsPath, $extracted['twigGlobals'], $pluginName, $meta, $force);
            if ($result['written']) {
                $results['generated'][] = $globalsPath;
                $autoGenerated[] = $globalsPath;
            } else {
                $results['skipped'][] = $globalsPath . ' (already exists)';
            }
        }

        // 6. Shared features reference
        if (!empty($extracted['sharedFeatures'])) {
            $featuresPath = 'developers/shared-features.md';
            $result = $this->generateSharedFeaturesDoc($docsPath, $extracted['sharedFeatures'], $pluginName, $meta, $force);
            if ($result['written']) {
                $results['generated'][] = $featuresPath;
                $autoGenerated[] = $featuresPath;
            } else {
                $results['skipped'][] = $featuresPath . ' (already exists)';
            }
        }

        // 7. Events reference
        if (!empty($extracted['events'])) {
            $eventsPath = 'developers/events.md';
            $result = $this->generateEventsDoc($docsPath, $extracted['events'], $pluginName, $meta, $force);
            if ($result['written']) {
                $results['generated'][] = $eventsPath;
                $autoGenerated[] = $eventsPath;
            } else {
                $results['skipped'][] = $eventsPath . ' (already exists)';
            }
        }

        // 8. Integrations reference
        if (!empty($extracted['integrations'])) {
            $integrationsPath = 'developers/integrations.md';
            $result = $this->generateIntegrationsDoc($docsPath, $extracted['integrations'], $pluginName, $meta, $force);
            if ($result['written']) {
                $results['generated'][] = $integrationsPath;
                $autoGenerated[] = $integrationsPath;
            } else {
                $results['skipped'][] = $integrationsPath . ' (already exists)';
            }
        }

        // 9. GraphQL reference
        if (!empty($extracted['graphql']) && $extracted['graphql']['enabled']) {
            $graphqlPath = 'developers/graphql.md';
            $result = $this->generateGraphQLDoc($docsPath, $extracted['graphql'], $pluginName, $meta, $force);
            if ($result['written']) {
                $results['generated'][] = $graphqlPath;
                $autoGenerated[] = $graphqlPath;
            } else {
                $results['skipped'][] = $graphqlPath . ' (already exists)';
            }
        }

        // Generate boilerplate manual files (only if they don't exist)
        $manualFiles = $this->generateBoilerplateFiles($docsPath, $pluginName, $pluginHandle, $meta);
        $results['generated'] = array_merge($results['generated'], $manualFiles);

        // Generate .sidebar.json (hidden file, like Verbb)
        $this->generateSidebar($docsPath, $pluginHandle, $autoGenerated, $manualFiles);
        $results['generated'][] = '.sidebar.json';

        // Generate plugin.json
        $this->generatePluginJson($docsPath, $composer);
        $results['generated'][] = 'plugin.json';

        // Update meta
        $meta['generated'] = $autoGenerated;
        $meta['manual'] = array_diff($manualFiles, $autoGenerated);
        $meta['lastGenerated'] = date('c');
        $this->saveMeta($pluginPath, $meta);

        return $results;
    }

    /**
     * Generate configuration reference documentation
     */
    private function generateConfigurationDoc(string $docsPath, array $settings, string $pluginName, array $meta, bool $force): array
    {
        $filePath = $docsPath . '/get-started/configuration.md';

        // Check if file exists and is not auto-generated
        if (file_exists($filePath) && !$force && !in_array('get-started/configuration.md', $meta['generated'] ?? [])) {
            return ['written' => false];
        }

        FileHelper::createDirectory(dirname($filePath));

        $content = "# Configuration\n\n";
        $content .= "Configure {$pluginName} by creating a config file in your `config/` directory.\n\n";
        $content .= "## Configuration Options\n\n";
        $content .= "| Option | Type | Default | Description |\n";
        $content .= "|--------|------|---------|-------------|\n";

        foreach ($settings as $setting) {
            $default = $setting['default'] ?? 'null';
            if ($default === '') {
                $default = "''";
            } elseif (is_string($default) && $default !== 'null' && $default !== 'true' && $default !== 'false') {
                $default = "`'{$default}'`";
            } else {
                $default = "`{$default}`";
            }

            $content .= "| `{$setting['name']}` | `{$setting['type']}` | {$default} | {$setting['description']} |\n";
        }

        $content .= "\n## Example Configuration\n\n";
        $content .= "```php\n";
        $content .= "<?php\n";
        $content .= "// config/{plugin-handle}.php\n\n";
        $content .= "return [\n";
        $content .= "    '*' => [\n";

        foreach ($settings as $setting) {
            $default = $setting['default'] ?? 'null';
            if ($default === '' || $default === "''") {
                $default = "''";
            } elseif ($default === 'true' || $default === 'false' || $default === 'null' || is_numeric($default)) {
                // Keep as-is
            } else {
                $default = "'{$default}'";
            }
            $content .= "        '{$setting['name']}' => {$default},\n";
        }

        $content .= "    ],\n";
        $content .= "];\n";
        $content .= "```\n";

        file_put_contents($filePath, $content);

        return ['written' => true];
    }

    /**
     * Generate template variables reference documentation
     */
    private function generateVariablesDoc(string $docsPath, array $variables, string $pluginName, string $pluginHandle, array $meta, bool $force): array
    {
        $filePath = $docsPath . '/developers/template-variables.md';

        if (file_exists($filePath) && !$force && !in_array('developers/template-variables.md', $meta['generated'] ?? [])) {
            return ['written' => false];
        }

        FileHelper::createDirectory(dirname($filePath));

        // Group by variable name
        $grouped = [];
        foreach ($variables as $var) {
            $grouped[$var['variableName']][] = $var;
        }

        $content = "# Template Variables\n\n";
        $content .= "{$pluginName} provides Twig variables for use in your templates.\n\n";

        foreach ($grouped as $varName => $methods) {
            $content .= "## `craft.{$varName}`\n\n";

            foreach ($methods as $method) {
                $content .= "### `{$method['method']}()`\n\n";

                if ($method['description']) {
                    $content .= "{$method['description']}\n\n";
                }

                if ($method['usage']) {
                    $content .= "```twig\n{$method['usage']}\n```\n\n";
                }

                if (!empty($method['parameters'])) {
                    $content .= "**Parameters:**\n\n";
                    $content .= "| Parameter | Type | Description |\n";
                    $content .= "|-----------|------|-------------|\n";

                    foreach ($method['parameters'] as $param) {
                        $content .= "| `{$param['name']}` | `{$param['type']}` | {$param['description']} |\n";
                    }

                    $content .= "\n";
                }

                if ($method['returnType']) {
                    $content .= "**Returns:** `{$method['returnType']}`\n\n";
                }

                $content .= "---\n\n";
            }
        }

        file_put_contents($filePath, $content);

        return ['written' => true];
    }

    /**
     * Generate console commands reference documentation
     */
    private function generateCommandsDoc(string $docsPath, array $commands, string $pluginName, array $meta, bool $force): array
    {
        $filePath = $docsPath . '/developers/console-commands.md';

        if (file_exists($filePath) && !$force && !in_array('developers/console-commands.md', $meta['generated'] ?? [])) {
            return ['written' => false];
        }

        FileHelper::createDirectory(dirname($filePath));

        $content = "# Console Commands\n\n";
        $content .= "{$pluginName} provides the following console commands.\n\n";

        foreach ($commands as $cmd) {
            $content .= "## `{$cmd['command']}`\n\n";

            if ($cmd['description']) {
                $content .= "{$cmd['description']}\n\n";
            }

            // Build usage example
            $args = '';
            if (!empty($cmd['parameters'])) {
                foreach ($cmd['parameters'] as $param) {
                    if ($param['default'] === null) {
                        $args .= " <{$param['name']}>";
                    } else {
                        $args .= " [{$param['name']}]";
                    }
                }
            }

            $content .= "```bash title=\"PHP\"\nphp craft {$cmd['command']}{$args}\n```\n\n";
            $content .= "```bash title=\"DDEV\"\nddev craft {$cmd['command']}{$args}\n```\n\n";

            if (!empty($cmd['parameters'])) {
                $content .= "**Arguments:**\n\n";
                $content .= "| Argument | Type | Description |\n";
                $content .= "|----------|------|-------------|\n";

                foreach ($cmd['parameters'] as $param) {
                    $required = $param['default'] === null ? 'Required' : 'Optional';
                    $content .= "| `{$param['name']}` | `{$param['type']}` | {$required} |\n";
                }

                $content .= "\n";
            }

            if (!empty($cmd['options'])) {
                $content .= "**Options:**\n\n";
                $content .= "| Option | Type | Description |\n";
                $content .= "|--------|------|-------------|\n";

                foreach ($cmd['options'] as $opt) {
                    $content .= "| `--{$opt['name']}` | `{$opt['type']}` | {$opt['description']} |\n";
                }

                $content .= "\n";
            }

            $content .= "---\n\n";
        }

        file_put_contents($filePath, $content);

        return ['written' => true];
    }

    /**
     * Generate permissions reference documentation with grouped nesting
     */
    private function generatePermissionsDoc(string $docsPath, array $permissionGroups, string $pluginName, array $meta, bool $force): array
    {
        $filePath = $docsPath . '/developers/permissions.md';

        if (file_exists($filePath) && !$force && !in_array('developers/permissions.md', $meta['generated'] ?? [])) {
            return ['written' => false];
        }

        FileHelper::createDirectory(dirname($filePath));

        $content = "# Permissions\n\n";
        $content .= "{$pluginName} registers granular permissions that can be assigned to user groups via **Settings → Users → User Groups → [Group Name] → {$pluginName}**.\n\n";
        $content .= "## Permission Structure\n\n";

        // Find first permission handle for usage examples
        $firstHandle = '';

        foreach ($permissionGroups as $group) {
            $content .= "### {$group['group']}\n\n";
            $content .= "| Permission | Description |\n";
            $content .= "|------------|-------------|\n";

            foreach ($group['permissions'] as $perm) {
                if (empty($firstHandle)) {
                    $firstHandle = $perm['handle'];
                }

                $hasNested = !empty($perm['nested']);
                $boldOpen = $hasNested ? '**' : '';
                $boldClose = $hasNested ? '**' : '';
                $suffix = $hasNested ? ' (parent)' : '';

                $content .= "| {$boldOpen}`{$perm['handle']}`{$boldClose} | {$perm['label']}{$suffix} |\n";

                if ($hasNested) {
                    foreach ($perm['nested'] as $child) {
                        $content .= "| └─ `{$child['handle']}` | {$child['label']} |\n";
                    }
                }
            }

            $content .= "\n";
        }

        // Usage examples
        if (empty($firstHandle)) {
            $firstHandle = 'pluginHandle:manageItems';
        }

        $content .= "## Checking Permissions\n\n";
        $content .= "In Twig:\n\n";
        $content .= "```twig\n";
        $content .= "{% if currentUser.can('{$firstHandle}') %}\n";
        $content .= "    {# User has permission #}\n";
        $content .= "{% endif %}\n";
        $content .= "```\n\n";
        $content .= "In PHP:\n\n";
        $content .= "```php\n";
        $content .= "if (Craft::\$app->getUser()->checkPermission('{$firstHandle}')) {\n";
        $content .= "    // User has permission\n";
        $content .= "}\n\n";
        $content .= "// In a controller\n";
        $content .= "\$this->requirePermission('{$firstHandle}');\n";
        $content .= "```\n\n";

        // Nested pattern explanation
        $content .= "## Nested Permission Pattern\n\n";
        $content .= "Craft's nested permissions are a UI convenience — the parent permission does not automatically grant child permissions.\n\n";
        $content .= "- **\"Manage\" permissions** are the top-level parent (grants access to the CP section)\n";
        $content .= "- **\"View\" permissions** control read access\n";
        $content .= "- **Write permissions** (create, edit, delete) control specific operations\n\n";
        $content .= "To give a user read-only access, grant the manage parent + view permission. For full access, also grant the specific write permissions needed.\n";

        file_put_contents($filePath, $content);

        return ['written' => true];
    }

    /**
     * Generate Twig globals reference documentation
     */
    private function generateTwigGlobalsDoc(string $docsPath, array $twigGlobals, string $pluginName, array $meta, bool $force): array
    {
        $filePath = $docsPath . '/developers/twig-globals.md';

        if (file_exists($filePath) && !$force && !in_array('developers/twig-globals.md', $meta['generated'] ?? [])) {
            return ['written' => false];
        }

        FileHelper::createDirectory(dirname($filePath));

        $content = "# Twig Globals\n\n";
        $content .= "{$pluginName} provides the following global variables in your Twig templates.\n\n";

        foreach ($twigGlobals as $global) {
            $content .= "## `{$global['name']}`\n\n";

            if (!empty($global['source'])) {
                $content .= "*Provided by `{$global['source']}`*\n\n";
            }

            if (!empty($global['properties'])) {
                $content .= "| Property | Description |\n";
                $content .= "|----------|-------------|\n";

                foreach ($global['properties'] as $prop) {
                    $content .= "| `{$global['name']}.{$prop['name']}` | {$prop['description']} |\n";
                }

                $content .= "\n### Examples\n\n";
                $content .= "```twig\n";

                foreach ($global['properties'] as $prop) {
                    if (!empty($prop['example'])) {
                        $content .= "{$prop['example']}\n";
                    }
                }

                $content .= "```\n\n";
            }

            $content .= "---\n\n";
        }

        file_put_contents($filePath, $content);

        return ['written' => true];
    }

    /**
     * Generate shared features reference documentation
     */
    private function generateSharedFeaturesDoc(string $docsPath, array $sharedFeatures, string $pluginName, array $meta, bool $force): array
    {
        $filePath = $docsPath . '/developers/shared-features.md';

        if (file_exists($filePath) && !$force && !in_array('developers/shared-features.md', $meta['generated'] ?? [])) {
            return ['written' => false];
        }

        FileHelper::createDirectory(dirname($filePath));

        $content = "# Shared Features\n\n";
        $content .= "{$pluginName} uses the following shared libraries and features.\n\n";

        // Group by source
        $grouped = [];
        foreach ($sharedFeatures as $feature) {
            $grouped[$feature['source']][] = $feature;
        }

        foreach ($grouped as $source => $features) {
            $content .= "## `{$source}`\n\n";

            $content .= "| Feature | Description |\n";
            $content .= "|---------|-------------|\n";

            foreach ($features as $feature) {
                $content .= "| `{$feature['feature']}` | {$feature['description']} |\n";
            }

            $content .= "\n### Details\n\n";

            foreach ($features as $feature) {
                $content .= "**{$feature['feature']}**\n\n";
                $content .= "{$feature['docs']}\n\n";
            }

            $content .= "---\n\n";
        }

        file_put_contents($filePath, $content);

        return ['written' => true];
    }

    /**
     * Generate events reference documentation
     */
    private function generateEventsDoc(string $docsPath, array $events, string $pluginName, array $meta, bool $force): array
    {
        $filePath = $docsPath . '/developers/events.md';

        if (file_exists($filePath) && !$force && !in_array('developers/events.md', $meta['generated'] ?? [])) {
            return ['written' => false];
        }

        FileHelper::createDirectory(dirname($filePath));

        $content = "# Events\n\n";
        $content .= "Events can be used to extend the functionality of {$pluginName}.\n\n";

        // Group events by service
        $grouped = [];
        foreach ($events as $event) {
            $serviceName = $event['service'] ?: 'Plugin';
            $grouped[$serviceName][] = $event;
        }

        foreach ($grouped as $serviceName => $serviceEvents) {
            $content .= "## {$serviceName} Events\n\n";

            foreach ($serviceEvents as $event) {
                $content .= "### The `{$event['name']}` event\n\n";

                // Only show description if it's meaningful (not just asterisks or whitespace)
                $desc = trim($event['description'] ?? '', " \t\n\r\0\x0B*");
                if (!empty($desc)) {
                    $content .= "{$desc}\n\n";
                }

                $content .= "```php\n";
                $content .= "use {$event['serviceClass']};\n";
                $content .= "use yii\\base\\Event;\n\n";
                $content .= "Event::on(\n";
                $content .= "    {$serviceName}::class,\n";
                $content .= "    {$serviceName}::{$event['constant']},\n";
                $content .= "    function(Event \$event) {\n";
                $content .= "        // Your code here\n";
                $content .= "    }\n";
                $content .= ");\n";
                $content .= "```\n\n";
            }
        }

        file_put_contents($filePath, $content);

        return ['written' => true];
    }

    /**
     * Generate integrations reference documentation
     */
    private function generateIntegrationsDoc(string $docsPath, array $integrations, string $pluginName, array $meta, bool $force): array
    {
        $filePath = $docsPath . '/developers/integrations.md';

        if (file_exists($filePath) && !$force && !in_array('developers/integrations.md', $meta['generated'] ?? [])) {
            return ['written' => false];
        }

        FileHelper::createDirectory(dirname($filePath));

        $content = "# Integrations\n\n";
        $content .= "{$pluginName} provides integrations with the following plugins and services.\n\n";

        $content .= "| Integration | Plugin | Description |\n";
        $content .= "|-------------|--------|-------------|\n";

        foreach ($integrations as $integration) {
            $plugin = $integration['integratesWith'] ?: 'Custom';
            // Clean description, fallback to auto-generated
            $desc = trim($integration['description'] ?? '', " \t\n\r\0\x0B*");
            if (empty($desc)) {
                $desc = 'Integration with ' . str_replace('Integration', '', $integration['class']);
            }
            $content .= "| `{$integration['class']}` | `{$plugin}` | {$desc} |\n";
        }

        $content .= "\n## Integration Details\n\n";

        foreach ($integrations as $integration) {
            $content .= "### {$integration['class']}\n\n";

            if ($integration['integratesWith']) {
                $content .= "**Integrates with:** `{$integration['integratesWith']}`\n\n";
            }

            // Clean description
            $desc = trim($integration['description'] ?? '', " \t\n\r\0\x0B*");
            if (!empty($desc)) {
                $content .= "{$desc}\n\n";
            }

            $content .= "---\n\n";
        }

        file_put_contents($filePath, $content);

        return ['written' => true];
    }

    /**
     * Generate GraphQL reference documentation
     */
    private function generateGraphQLDoc(string $docsPath, array $graphql, string $pluginName, array $meta, bool $force): array
    {
        $filePath = $docsPath . '/developers/graphql.md';

        if (file_exists($filePath) && !$force && !in_array('developers/graphql.md', $meta['generated'] ?? [])) {
            return ['written' => false];
        }

        FileHelper::createDirectory(dirname($filePath));

        $content = "# GraphQL\n\n";
        $content .= "{$pluginName} provides GraphQL support for headless applications.\n\n";

        if (!empty($graphql['types'])) {
            $content .= "## Types\n\n";
            $content .= "The following GraphQL types are available:\n\n";
            foreach ($graphql['types'] as $type) {
                $content .= "- `{$type}`\n";
            }
            $content .= "\n";
        }

        if (!empty($graphql['queries'])) {
            $content .= "## Queries\n\n";
            $content .= "The following GraphQL queries are available:\n\n";
            foreach ($graphql['queries'] as $query) {
                $content .= "- `{$query}`\n";
            }
            $content .= "\n";
        }

        if (!empty($graphql['mutations'])) {
            $content .= "## Mutations\n\n";
            $content .= "The following GraphQL mutations are available:\n\n";
            foreach ($graphql['mutations'] as $mutation) {
                $content .= "- `{$mutation}`\n";
            }
            $content .= "\n";
        }

        // If no specific types/queries/mutations found but GraphQL is enabled
        if (empty($graphql['types']) && empty($graphql['queries']) && empty($graphql['mutations'])) {
            $content .= "GraphQL support is enabled. See the plugin's GraphQL schema for available types and queries.\n\n";
        }

        file_put_contents($filePath, $content);

        return ['written' => true];
    }

    /**
     * Generate boilerplate manual files
     */
    private function generateBoilerplateFiles(string $docsPath, string $pluginName, string $pluginHandle, array $meta): array
    {
        $created = [];

        $boilerplate = [
            'get-started/installation.md' => $this->getInstallationTemplate($pluginName, $pluginHandle),
            'get-started/requirements.md' => $this->getRequirementsTemplate($pluginName),
        ];

        foreach ($boilerplate as $relativePath => $content) {
            $filePath = $docsPath . '/' . $relativePath;

            // Only create if doesn't exist
            if (!file_exists($filePath)) {
                FileHelper::createDirectory(dirname($filePath));
                file_put_contents($filePath, $content);
                $created[] = $relativePath;
            }
        }

        return $created;
    }

    /**
     * Generate .sidebar.json (hidden file, like Verbb)
     *
     * @param string $docsPath Path to docs directory
     * @param string $pluginHandle Plugin handle
     * @param array<string> $autoGenerated Auto-generated file paths
     * @param array<string> $manual Manual file paths
     */
    private function generateSidebar(string $docsPath, string $pluginHandle, array $autoGenerated, array $manual): void
    {
        $sections = [
            'Get Started' => [
                'get-started/requirements',
                'get-started/installation',
                'get-started/configuration',
            ],
            'Feature Tour' => [
                'feature-tour/overview',
                'feature-tour/multi-site',
                'feature-tour/custom-domain',
                'feature-tour/analytics',
                'feature-tour/qr-codes',
                'feature-tour/backups',
                'feature-tour/advanced',
            ],
            'Template Guides' => [
                'template-guides/usage',
                'template-guides/site-translations',
                'template-guides/managing-translations',
                'template-guides/csv-export',
                'template-guides/csv-import',
                'template-guides/php-export',
            ],
            'Integrations' => [
                'integrations/formie',
                'integrations/redirect-manager',
                'integrations/seomatic',
            ],
            'Developers' => [
                'developers/template-variables',
                'developers/twig-globals',
                'developers/console-commands',
                'developers/events',
                'developers/permissions',
                'developers/security',
                'developers/logging',
                'developers/graphql',
                'developers/api-reference',
                'developers/shared-features',
            ],
            'Resources' => [
                'resources/troubleshooting',
            ],
        ];

        // Sidebar display defaults per section
        // collapsable: false = always open, no toggle
        // open: default state when collapsable is true (active page section always forced open)
        $sectionDefaults = [
            'Get Started' => ['collapsable' => false],
            'Feature Tour' => ['collapsable' => true, 'open' => true],
            'Template Guides' => ['collapsable' => true, 'open' => true],
            'Developers' => ['collapsable' => true, 'open' => false],
            'Integrations' => ['collapsable' => true, 'open' => false],
            'Resources' => ['collapsable' => true, 'open' => false],
        ];

        $sidebar = [];

        foreach ($sections as $title => $children) {
            // Filter to only include files that exist
            $existingChildren = [];
            foreach ($children as $child) {
                if (file_exists($docsPath . '/' . $child . '.md')) {
                    $existingChildren[] = $child;
                }
            }

            // Only add section if it has children
            if ($existingChildren !== []) {
                $defaults = $sectionDefaults[$title];
                $entry = [
                    'title' => $title,
                    'collapsable' => $defaults['collapsable'],
                ];
                if ($defaults['collapsable']) {
                    $entry['open'] = $defaults['open'];
                }
                $entry['children'] = $existingChildren;
                $sidebar[] = $entry;
            }
        }

        // Use hidden file like Verbb
        $sidebarPath = $docsPath . '/.sidebar.json';
        file_put_contents($sidebarPath, json_encode($sidebar, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    }

    /**
     * Generate plugin.json
     */
    private function generatePluginJson(string $docsPath, array $composer): void
    {
        $pluginJson = [
            'name' => $composer['extra']['name'] ?? 'Unknown Plugin',
            'handle' => $composer['extra']['handle'] ?? 'unknown',
            'description' => $composer['description'] ?? '',
            'version' => $composer['version'] ?? '1.0.0',
            'developer' => $composer['extra']['developer'] ?? '',
            'developerUrl' => $composer['extra']['developerUrl'] ?? '',
            'documentationUrl' => $composer['extra']['documentationUrl'] ?? '',
        ];

        $pluginJsonPath = $docsPath . '/plugin.json';
        file_put_contents($pluginJsonPath, json_encode($pluginJson, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    }

    /**
     * Load .docs-meta.json
     */
    private function loadMeta(string $pluginPath): array
    {
        $metaPath = $pluginPath . '/docs/.docs-meta.json';

        // Fallback: check old location (plugin root) for migration
        if (!file_exists($metaPath) && file_exists($pluginPath . '/.docs-meta.json')) {
            return json_decode(file_get_contents($pluginPath . '/.docs-meta.json'), true) ?? [];
        }

        if (file_exists($metaPath)) {
            return json_decode(file_get_contents($metaPath), true) ?? [];
        }

        return [
            'generated' => [],
            'manual' => [],
            'lastGenerated' => null,
        ];
    }

    /**
     * Save .docs-meta.json
     */
    private function saveMeta(string $pluginPath, array $meta): void
    {
        $metaPath = $pluginPath . '/docs/.docs-meta.json';
        file_put_contents($metaPath, json_encode($meta, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    }

    /**
     * Get installation template
     */
    private function getInstallationTemplate(string $pluginName, string $pluginHandle): string
    {
        return <<<MD
# Installation & Setup

> **Pre-Release:** {$pluginName} is in active development and not yet available on the Craft Plugin Store. Install via Composer for now.

## Composer

Add the package to your project using Composer and the command line.

1. Open your terminal and go to your Craft project:

```bash
cd /path/to/project
```

2. Then tell Composer to require the plugin, and Craft to install it:

```bash title="Composer"
composer require lindemannrock/craft-{$pluginHandle} && php craft plugin/install {$pluginHandle}
```

```bash title="DDEV"
ddev composer require lindemannrock/craft-{$pluginHandle} && ddev craft plugin/install {$pluginHandle}
```

MD;
    }

    /**
     * Get requirements template
     */
    private function getRequirementsTemplate(string $pluginName): string
    {
        return <<<MD
# Requirements

## Craft CMS

{$pluginName} requires Craft CMS 5.0 or greater.

## PHP

{$pluginName} requires PHP 8.2 or greater.

## Dependencies

The following packages are installed automatically via Composer:

| Package | Purpose |
|---------|---------|
| `lindemannrock/craft-plugin-base` ^5.0 | Shared base plugin utilities (helpers, traits, layouts) |
| `lindemannrock/craft-logging-library` ^5.0 | Plugin logging and log viewer |

MD;
    }
}
